config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'static#home'

  resources :projects
  resources :comments, only: [:create]
  scope '/blog' do
    resources :posts
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :comments, :as => :commentable, dependent: :destroy
  belongs_to :commentable, :polymorphic => true

  validates :author, presence: true, length: { minimum: 3, maximum: 50}
  validates :content, presence: true, length: { minimum: 2, maximum: 500}
  validates :commentable, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, :as => :commentable

  validates :title, presence: true, length: { minimum: 3, maximum: 144 }
  validates :body, presence: true, length: { minimum: 2 }
  #validate slug?
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_attached_file :banner, styles: { banner:"1920x300>", show:"1024x300#" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :banner, content_type: /\Aimage\/.*\Z/
  validates :title, presence: true, length: { minimum: 3, maximum: 144}, uniqueness: true
  validates :description, presence: true, length: { minimum: 3}
  validates :banner, presence: true




end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :content, presence: true, length: {minimum: 2, maximum: 30}, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @commentable = Post.find(params[:comment][:post_id]) if params[:comment][:post_id]
    @comment = @commentable.comments.build(comment_params)
    
    if @comment.save
      flash[:success] = "Comment submited"
    else
      flash[:danger] = "Comment failed"
    end

    redirect_to @commentable
  end

  private

    def comment_params
      params.require(:comment).permit(:author,:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_post, only: [:edit,:update,:destroy]

  def show
    @comment = Comment.new
    @post = Post.includes(:comments).find(params[:id])
  end

  def index
    @category = params[:category]
    @posts = post_feed @category
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      flash[:success] = "Post successfully created!"

      #create tags from string separated by a ;
      params[:tags].split(";").each do |tag|
        @tag = Tag.find_or_create_by(content: tag.strip)
        Tagging.create(post_id: @post.id, tag_id: @tag.id)
      end

      redirect_to @post
    else
      flash[:danger] = "Failed to create post"
      render 'new'
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully updated!"
      redirect_to @post
    else
      flash[:danger] = "Failed to create post!"
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post Destroyed"
    redirect_to posts_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :id)
    end

    def post_feed category
      posts = []
      if params[:category]
        marked  = Tagging.where(tag_id: Tag.find_by(content: params[:category])).includes(:post)
        marked.each { |mark| posts << mark.post }
      else
        posts = Post.all.order(created_at: :desc)
      end

      posts
    end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @projects = Project.all.order(created_at: :desc).paginate(page: params[:page], per_page: 4)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      flash['success'] = "Project Successfully created!"
      redirect_to @project
    else
      flash['danger'] = "Failed to Create Project"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash['success'] = "Project Successfully updated!"
      redirect_to @project
    else
      flash['danger'] = "Failed to Update Project"
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title,:description, :banner, :project_url, :github_url)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/comments/_comment_form.html.erb
<%= simple_form_for @comment, html: {multipart: true} do |form| %>
  <h2><%= "Leave a comment below:" %></h2>
  <%= form.hidden_field :post_id, :value => @post.id%>
  <%= form.input :author, label: "Name: " %>
  <%= form.input :content, label: "Comment: " %>
  <%= form.button :button, "Post it!".html_safe, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<%end%>

app/views/layouts/_footer.html.slim
footer.footer role="content-info"
  ul
    li
      p Curitiba, Brazil 2016
  .footer-secondary-links
    ul
      li
        p All the content of my authorship in this site is under the MIT license unless specified.

app/views/layouts/_header.html.slim
header.header-2 role="content-info"
  ul
    li
      = link_to "Luiz Vasconcellos", root_path
  .header-secondary-links
    ul
      li
        = link_to "Home", root_path
      li
        = link_to "Projects", projects_path
      li
        = link_to "Blog", posts_path
      - if current_admin
        li
          = link_to "Sign out", destroy_admin_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title Luiz Vasconcellos' Blog
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    link href='//fonts.googleapis.com/css?family=Lusitana:400,700' rel='stylesheet' type='text/css'
    link href='//fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'
    link href='//fonts.googleapis.com/css?family=Merriweather+Sans:400,300,300italic,400italic,700italic,700,800,800italic' rel='stylesheet' type='text/css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  body
    = render 'layouts/header'
    .wrapper
      - flash.each do |message_type, message|
        div class="flash-#{message_type}"
          p = message
      = yield
    = render 'layouts/footer'

app/views/posts/_post.html.slim
article.post.type-system-serif
  h1 = @post.title
  p.date = "Posted " + @post.created_at.strftime("%d %b %Y")
  p.author Author: Luiz Vasconcellos
  .content
    = raw(@post.body)
  = render partial: "post_tags", locals: { tags: @post.tags}
  hr

app/views/posts/_post_abstract.html.slim
article.item.type-system-serif
  h1 = link_to post.title, post
  p.date
    em = "Posted " + time_ago_in_words(post.created_at) + " ago by Luiz Vasconcellos"
  p = raw(post.body)
  = link_to raw("Read more &rsaquo;"), post, class: "read-more"
  = render partial: "post_tags", locals: { tags: post.tags}
  hr

app/views/posts/_post_comments.html.slim
section.comment-container
  h2 Comments
  #comments-list
    - comments.each do |comment|
      .comment
        .comment-content
          h6 = "Posted " + comment.created_at.strftime("%d %b %Y at %H:%M")
          h1 = comment.author + " :"
          p = comment.content

app/views/posts/_post_form.html.slim
= form_tag posts_path(@post) do
  = fields_for @post do |f|
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :body
      = f.text_area :body
  = label_tag "Tags"
  = text_field_tag :tags
  .actions
    button class= "sqr-btn" id="post-preview" type="button" Preview
    = submit_tag "Submit Post"

app/views/posts/_post_tags.html.slim
p.author.post-tags
  | Tags:
  - tags.each do |tag|
    = link_to " " + tag.content , posts_path(category: tag.content)
    = comma = ", " unless tag == tags.last

app/views/posts/edit.html.slim
section.project-form-page
  h1.page-title Edit Post
  = form_for @post do |form|
    = fields_for @post do |f|
      .field
        = f.label :title
        = f.text_field :title
      .field
        = f.label :body
        = f.text_area :body
    = label_tag "Tags"
    = text_field_tag :tags
    .actions
      = submit_tag "Submit Post"

app/views/posts/index.html.slim
section.post-list
  .list
    - @posts.each do  |post|
      = render partial: "post_abstract", locals: { post: post}

app/views/posts/new.html.slim
section.project-form-page
  h1.page-title New Post
  = render 'post_form'

app/views/posts/show.html.slim
section.post-container
  h5 = link_to "← All Posts", posts_path
  = render @post
  = render "comments/comment_form"
  = render partial: "post_comments", locals: { comments: @post.comments}

app/views/projects/_project_form.html.slim
= simple_form_for @project do |f|
  = f.input :title
  = f.input :project_url, label: 'URL: '
  = f.input :github_url, label: 'Github: '
  = f.input :description
  = f.input :banner, as: :file
  .actions
    button class= "sqr-btn" id="project-preview" type="button" Preview
    = f.button :submit

app/views/projects/edit.html.slim
section.project-form-page
  h1.page-title Edit Project
  = render 'project_form'

app/views/projects/index.html.slim
section.project-index
  div.index-header
    h1 My Projects
    h2 Here are some of my favorites, all made with love.
  = will_paginate @projects
  div.index-container
    - @projects.each do |project|
      div.project-thumb
        = image_tag project.banner.url(:banner)
        .hover
        = link_to project.title, project, class:"link"

app/views/projects/new.html.slim
section.project-form-page
  h1.page-title New Project
  = render 'project_form'

app/views/projects/show.html.slim
section.project-page
  div.project-container
    h5 = link_to "← All Projects", projects_path
    h1.project-title
      =  @project.title
      - if @project.project_url
        span.title-link = link_to raw(fa_icon("fort-awesome") + " To Project"), @project.project_url, :target => "_blank"
      - if @project.github_url
        span.title-link = link_to raw(fa_icon("code-fork") + " To Repository") , @project.github_url, :target => "_blank"
    h6 = "Submitted " + time_ago_in_words(@project.created_at) + " ago"

    = image_tag @project.banner.url(:show)
    .project-text
      = raw(@project.description)